"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "example-api"
__version__: str = "0.0.2"
__openapi_doc_version__: str = "1.1.0"
__gen_version__: str = "2.798.0"
__user_agent__: str = "speakeasy-sdk/python 0.0.2 2.798.0 1.1.0 example-api"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
