"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from example_api.types import BaseModel
from typing_extensions import TypedDict


class CreateUserRequestTypedDict(TypedDict):
    email: str
    r"""User's email address"""
    name: str
    r"""User's full name"""


class CreateUserRequest(BaseModel):
    email: str
    r"""User's email address"""

    name: str
    r"""User's full name"""
