"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from example_api.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UserTypedDict(TypedDict):
    id: str
    r"""Unique identifier for the user"""
    email: str
    r"""User's email address"""
    name: str
    r"""User's full name"""
    created_at: NotRequired[datetime]
    r"""When the user was created"""


class User(BaseModel):
    id: str
    r"""Unique identifier for the user"""

    email: str
    r"""User's email address"""

    name: str
    r"""User's full name"""

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None
    r"""When the user was created"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
